@startuml
start
:获取系统相关参数;
:判断数据库连接;
if (是否正常连接?) then (正常连接)
:正常执行;
else (找不到连接)
  if(用户是否为生产环境?) then(是生产环境)
  :不执行询问框;
  :中断执行，输出错误信息
  >>>>;
  else(是开发环境)
  :弹出确认框，
  询问用户是否执行初始化数据库;
  :数据库连接正常;
  endif
endif

:启动springboot;
stop
@enduml